name = "MMFNEXUS"
uuid = "10f02407-cee8-4d2b-96f7-1b77de738a58"
authors = ["Bram D. Alferink <bramalferink@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
FFTW = "1.10.0"
HDF5 = "0.17.2"
Images = "0.26.2"
LinearAlgebra = "1.11.0"
Logging = "1.11.0"
Plots = "1.41.5"
Roots = "2.2.10"
Statistics = "1.11.1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
